### ISSUE TITLE
Use event-bus with class object

### ISSUE THREAD

**Issue by bkupidura** [seanpar203/event-bus#1]
Hello, great lib, but ... :)

It is possible to use event-bus with class object/thread?

```

#!/usr/bin/env python3
import time
from threading import Thread

from event_bus import EventBus


bus = EventBus()

class Test(Thread):
    def __init__(self, bus):
        super(Test, self).__init__()
        self.bus = bus
        self.name = 'test'
        self.daemon = True

    @bus.on('test')
    def test(self):
        print('test')

test = Test(bus)

test.start()

while True:
    bus.emit('test')
    time.sleep(5)

```

This ends up with `TypeError: test() missing 1 required positional argument: 'self'`

**Comment by seanpar203** [comment]
So this isn't an issue, you're trying to call a instance of the Test object without giving the `test` method a instance of a Test object.

The code below prints test every 5 seconds, all that was required as passing an instance of `Test` to the `test` method which then becomes the `self` argument in `test(self):`

`# !/usr/bin/env python3
import time
from threading import Thread

from event_bus import EventBus

if __name__ == '__main__':
    bus = EventBus()


    class Test(Thread):
        def __init__(self, bus):
            super(Test, self).__init__()
            self.bus = bus
            self.name = 'test'
            self.daemon = True

        @bus.on('test')
        def test(self):
            print('test')


    test = Test(bus)

    test.start()

    while True:
        bus.emit('test', test)
        time.sleep(5)
`

**Comment by victorromeo** [comment]
Hi,

Great package.  I hope you keep this alive.

May I follow up on this issue again? I don't think your worked example really cut to the issue here.
Your solution required passing a global instance in, as a bus argument, whereas this is typically meant to be determined late.

Consider where the bus is passing the same event to multiple classes.  The 'self' argument could not be satisfied by your approach, as only one class would match.  The problem is somewhat worse when the bus event emitting source is also a class.

```
class teacher():
    @bus.on(*school_bell")
    def bell(self, bell):
        print(bell.time)

class student():
    @bus.on("school_bell")
    def bell(self, bell)
        print(bell.time)

class bell():
    def ring_bell(self):
        bus.emit("school_bell",  self)
   
    def time(self):
        return "Hometime"

```


Thoughts?

**Comment by victorromeo** [comment]
As a follow up, I've found that swapping the @bus.on('event_name') for bus.add_event(callback,'event_name') may be one work around.
